### ISSUE TITLE
Hey..

### ISSUE THREAD

**Issue by varughesefebin** [Mindkraft/Mindkraft-Registration-Portal#2]
Hey @Paulwin

**Comment by Paulwin** [comment]
Hello

**Comment by varughesefebin** [comment]
This is where you write stuff

**Comment by varughesefebin** [comment]
I mean where u kindaa chat...

**Comment by Paulwin** [comment]
Okay... This is Fun....

**Comment by varughesefebin** [comment]
If you face any issue then create a new thread and put ur queries..

**Comment by varughesefebin** [comment]
Theek hai,,
??

**Comment by Paulwin** [comment]
Okay... So how to get started

**Comment by Paulwin** [comment]
What to do next...

**Comment by varughesefebin** [comment]
Go to the code tab

**Comment by Paulwin** [comment]
then...

**Comment by varughesefebin** [comment]
Leave this page open... open the code tab in a new tab of ur browser

**Comment by varughesefebin** [comment]
Do you see clone or download?

**Comment by Paulwin** [comment]
done..

**Comment by Paulwin** [comment]
yes

**Comment by varughesefebin** [comment]
by pressing **Ctrl + Enter** you can directly send this message without clicking on comment..

**Comment by Paulwin** [comment]
Downloaded

**Comment by varughesefebin** [comment]
Now open the project in your pc...and you can view stuff...

**Comment by Paulwin** [comment]
Okay ... Thank you for Ctrl + Enter

**Comment by varughesefebin** [comment]
after that make any changes you want.. and edit it in the code tab..

**Comment by Paulwin** [comment]
Okay

**Comment by varughesefebin** [comment]
after editing you'll get two options.. Create a pull request or directly add to the master.. always create a pull request...thats good practice

**Comment by varughesefebin** [comment]
i'll make some changes now and create a pull request...

**Comment by varughesefebin** [comment]
you check it out..

**Comment by varughesefebin** [comment]
you have to approve...then only my changes will be reflected in the master code..

**Comment by Paulwin** [comment]
Oh...

**Comment by varughesefebin** [comment]
you there?

**Comment by varughesefebin** [comment]
i created a pull request...

**Comment by Paulwin** [comment]
Yes...I was checking with the web site

**Comment by varughesefebin** [comment]
made some changes... after reviewing if you have no problem with the change then click on merge..

**Comment by Paulwin** [comment]
oh ...

**Comment by varughesefebin** [comment]
sorry

**Comment by varughesefebin** [comment]
just realized you just have read access now...

**Comment by varughesefebin** [comment]
let me change it to write access...

**Comment by Paulwin** [comment]
Okay...Saw your Profile ..By the way

**Comment by varughesefebin** [comment]
ok...

**Comment by varughesefebin** [comment]
u have write access

**Comment by varughesefebin** [comment]
go to pull request tab again...you will see Merge Pull Request

**Comment by varughesefebin** [comment]
Click on that...

**Comment by Paulwin** [comment]
did i do it right..

**Comment by Paulwin** [comment]
Febin....

**Comment by varughesefebin** [comment]
yeah... :)

**Comment by varughesefebin** [comment]
now the change i made has come to the master file..

**Comment by Paulwin** [comment]
Okay...

**Comment by varughesefebin** [comment]
I have the login page in .aspx... just for your info..

**Comment by Paulwin** [comment]
yes..It is open in the browser

**Comment by varughesefebin** [comment]
cool

**Comment by varughesefebin** [comment]
everytime you start working on it... first download.. and then start working... so you will be working with the latest update,,..

**Comment by Paulwin** [comment]
I thought of doing little changes...

**Comment by varughesefebin** [comment]
and once you finish working just make a pull request..

**Comment by varughesefebin** [comment]
yeah...go ahead...

**Comment by varughesefebin** [comment]
Send me a screenshot of how it looks on ur browser... the aspx wala page..

**Comment by Paulwin** [comment]
I am sending it in your whatsapp..
Is it okay

**Comment by Paulwin** [comment]
Listen ... sorry for the inconvenience that my phone is causing....

**Comment by varughesefebin** [comment]
I'm closing this issue. Feel free to open a new issue anytime. Btw.. solved the font wala problem. Now it wont create a problem in any pc. i have put a pull request.. u review it and merge it. Thanks.
